# Generated by Django 3.1.7 on 2021-03-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_auto_20210312_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('fuji', 'fuji'), ('nikon', 'nikon'), ('red', 'red'), ('sony', 'sony'), ('canon', 'canon'), ('other', 'other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('mobile_review', 'mobile_review'), ('vlogs', 'vlogs'), ('code', 'code'), ('comedy', 'comedy'), ('cooking', 'cooking'), ('gaming', 'gaming'), ('film_making', 'film_making')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('large', 'large'), ('small', 'small'), ('solo', 'solo')], max_length=255),
        ),
    ]
