# Generated by Django 3.1.7 on 2021-03-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0004_auto_20210313_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('canon', 'canon'), ('fuji', 'fuji'), ('red', 'red'), ('other', 'other'), ('sony', 'sony'), ('nikon', 'nikon')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('gaming', 'gaming'), ('mobile_review', 'mobile_review'), ('comedy', 'comedy'), ('code', 'code'), ('cooking', 'cooking'), ('film_making', 'film_making'), ('vlogs', 'vlogs')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('solo', 'solo'), ('small', 'small'), ('large', 'large')], max_length=255),
        ),
    ]
